from django.db import models
import uuid
# Create your models here.
class Formlar(models.Model):
    form_id = models.CharField(primary_key=True, max_length=36, default=uuid.uuid4, editable=False)
    ad = models.CharField(max_length=100)
    soyad = models.CharField(max_length=50)
    kaynak = models.CharField(max_length=100, blank=True)
    sube = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=100, blank=True)
    cepno = models.CharField(max_length=20, blank=True)
    iys_sms = models.BooleanField(null=True)
    iys_arama = models.BooleanField(null=True)
    iys_email = models.BooleanField(null=True)
    k_veriisleme = models.BooleanField(null=True)
    k_veripaylasimi = models.BooleanField(null=True)
    k_yurtdisi = models.BooleanField(null=True)
    k_aydinlatmaMetin = models.BooleanField(null=True)
    formOlusturmaTarihi = models.DateTimeField(auto_now_add=True)
    userIp = models.CharField(max_length=100, blank=True)
    userCihaz = models.CharField(max_length=100, blank=True)
    userOs= models.CharField(max_length=100, blank=True)
    userBrowser = models.CharField(max_length=150, blank=True)
    formOnayTarihi = models.DateTimeField(blank=True, null=True)
    code = models.CharField(max_length=10, blank=True)
    code_error = models.CharField(max_length=100, blank=True)
class Onaylar(models.Model):
    onay_id = models.CharField(primary_key=True, max_length=36, default=uuid.uuid4, editable=False)
    transactionid = models.CharField(max_length=100, blank=True)
    submitid = models.CharField(max_length=100, blank=True)
    resultstatus = models.CharField(max_length=20, null=True)
    user_refcode = models.CharField(max_length=100, null=True)
    status = models.CharField(max_length=10, blank=True)
    type = models.CharField(max_length=10, null=True)
    source = models.CharField(max_length=20, blank=True)
    recipientType = models.CharField(max_length=20, blank=True)
    recipient = models.CharField(max_length=120, blank=True)
    creationdate = models.DateTimeField(blank=True, null=True)
    consentDate = models.DateTimeField(blank=True, null=True)
    errcode = models.CharField(max_length=20, blank=True)
    errmsg = models.CharField(max_length=100, blank=True)
     
