# Generated by Django 4.2.4 on 2023-08-15 20:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formlar',
            fields=[
                ('kisi_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=50)),
                ('kaynak', models.CharField(blank=True, max_length=100)),
                ('sube', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('cepno', models.CharField(max_length=20)),
                ('iys_sms', models.BooleanField()),
                ('iys_arama', models.BooleanField()),
                ('iys_email', models.BooleanField()),
                ('k_veriisleme', models.BooleanField()),
                ('k_veripaylasimi', models.BooleanField()),
                ('k_yurtdisi', models.BooleanField()),
                ('k_aydinlatmaMetin', models.BooleanField()),
                ('formOlusturmaTarihi', models.DateTimeField(auto_now_add=True)),
                ('userIp', models.CharField(blank=True, max_length=20)),
                ('userCihaz', models.CharField(blank=True, max_length=50)),
                ('userOs', models.CharField(blank=True, max_length=50)),
                ('userBrowser', models.CharField(blank=True, max_length=50)),
                ('formOnayTarihi', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('code_error', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Onaylar',
            fields=[
                ('onay_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('transactionid', models.CharField(blank=True, max_length=100)),
                ('submitid', models.CharField(blank=True, max_length=100)),
                ('resultstatus', models.CharField(max_length=20, null=True)),
                ('user_refcode', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('type', models.CharField(max_length=10, null=True)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('recipientType', models.CharField(blank=True, max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=120)),
                ('creationdate', models.DateTimeField(blank=True, null=True)),
                ('consentDate', models.DateTimeField(blank=True, null=True)),
                ('errcode', models.CharField(blank=True, max_length=20)),
                ('errmsg', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
