# Generated by Django 4.2.4 on 2023-08-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlar',
            name='iys_arama',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='iys_email',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='iys_sms',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='k_aydinlatmaMetin',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='k_veriisleme',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='k_veripaylasimi',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='k_yurtdisi',
            field=models.BooleanField(blank=True),
        ),
    ]
