# Generated by Django 4.2.4 on 2023-08-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsint', '0002_alter_formlar_iys_arama_alter_formlar_iys_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlar',
            name='iys_arama',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='iys_email',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='iys_sms',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='k_aydinlatmaMetin',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='k_veriisleme',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='k_veripaylasimi',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='k_yurtdisi',
            field=models.BooleanField(null=True),
        ),
    ]
