# Generated by Django 4.2.4 on 2023-08-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsint', '0003_alter_formlar_iys_arama_alter_formlar_iys_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlar',
            name='userBrowser',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='userCihaz',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='userIp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formlar',
            name='userOs',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
