# Generated by Django 4.2.4 on 2023-08-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsint', '0004_alter_formlar_userbrowser_alter_formlar_usercihaz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formlar',
            old_name='kisi_id',
            new_name='form_id',
        ),
    ]
