# Generated by Django 4.2.4 on 2023-08-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsint', '0005_rename_kisi_id_formlar_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlar',
            name='yontem',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
