# Generated by Django 4.2.4 on 2023-08-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsint', '0006_formlar_yontem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formlar',
            name='yontem',
        ),
    ]
