# Generated by Django 4.2.4 on 2023-08-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsint', '0007_remove_formlar_yontem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlar',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
